# Generated by Django 5.0.4 on 2024-04-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('womenclothes', '0002_remove_shoeswomen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoeswomen',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
