# Generated by Django 5.0.4 on 2024-04-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('xotira', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GameComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=255)),
            ],
        ),
    ]
