# Generated by Django 5.0.4 on 2024-04-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FahirliUstoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('ilmiy_unvoni', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('yonalish', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('speciality', models.CharField(max_length=255)),
            ],
        ),
    ]
