# Generated by Django 5.0.4 on 2024-04-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItCenterabout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('speciality', models.CharField(blank=True, max_length=255, null=True)),
                ('experiment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItCoursesAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
