# Generated by Django 5.0.4 on 2024-04-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manclothes', '0002_remove_shoes_name_remove_t_shirt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='t_shirt',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
