# Generated by Django 5.0.4 on 2024-04-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElekroMobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('power', models.CharField(max_length=255)),
            ],
        ),
    ]
