# Generated by Django 5.0.4 on 2024-04-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptopapple',
            name='year',
            field=models.IntegerField(),
        ),
    ]
