# Generated by Django 5.0.4 on 2024-04-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('tajribasi', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
            ],
        ),
    ]
