# Generated by Django 5.0.4 on 2024-04-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IqtidorliTalaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('xorijiy_til', models.CharField(max_length=255)),
                ('dasturlash_mahorati', models.CharField(max_length=255)),
                ('GPA', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('specialty', models.CharField(max_length=255)),
            ],
        ),
    ]
